---
# see https://gist.github.com/ibraheem4/ce5ccd3e4d7a65589ce84f2a3b7c23a3

- name: Install PostgreSQL
  homebrew:
    name: "postgresql@{{ postgresql_version }}"
    state: "{{ homebrew_package_state }}"

- name: Stop PostgreSQL
  shell: "brew services stop postgresql@{{ postgresql_version }}"

- name: Start PostgreSQL
  shell: "brew services start postgresql@{{ postgresql_version }}"

- name: Get brew prefix for PostgreSQL
  shell: "brew --prefix postgresql@{{ postgresql_version }}"
  register: brew_prefix_postgresql
  changed_when: False

- set_fact:
    postgresql_bin_path: "{{ brew_prefix_postgresql.stdout }}/bin"

- name: Add "~/.load_postgresql" file to add PostgreSQL to $PATH
  template:
    src: load_postgresql.j2
    dest: ~/.load_postgresql
    mode: "u=rxw,g=rx,o=rx"

- name: Check if user database exists
  shell: "{{ postgresql_bin_path }}/psql -lqt | cut -d \\| -f 1 | grep -qw {{ lookup('env','USER') }}"
  register: postgresql_user_database_exists
  ignore_errors: true
  changed_when: false

- name: Create user database
  shell: "{{ postgresql_bin_path }}/createdb {{ lookup('env','USER') }}"
  when: postgresql_user_database_exists.rc == 1

- name: Check if postgres user exists
  shell: "{{ postgresql_bin_path }}/psql -t -c '\\du' | cut -d \\| -f 1 | grep -qw postgres"
  register: postgresql_postgres_user_exists
  ignore_errors: true
  changed_when: false

- name: Create postgres user
  shell: "{{ postgresql_bin_path }}/createuser -s postgres"
  when: postgresql_postgres_user_exists.rc == 1

- name: Check if "postgres" database exists
  shell: "{{ postgresql_bin_path }}/psql -lqt | cut -d \\| -f 1 | grep -qw postgres"
  register: postgresql_postgres_database_exists
  ignore_errors: true
  changed_when: false

- name: Create "postgres" database
  shell: "{{ postgresql_bin_path }}/createdb -s postgres"
  when: postgresql_postgres_database_exists.rc == 1
