---

- name: Install mkcert and nss
  homebrew:
    name:
      - mkcert
      - nss
    state: "{{ homebrew_package_state }}"

- name: Setup mkcert
  shell: mkcert -install
  become: yes

- name: Create paths for certificates
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - "{{ openssl_private_path }}"
    - "{{ openssl_certs_path }}"

- name: Create certs
  shell: "mkcert -cert-file {{ openssl_certs_path }}/{{ item.name }}.pem -key-file {{ openssl_private_path }}/{{ item.name }}.pem {{ item.server_name }}"
  with_items: "{{ nginx_sites }}"

- name: Download cacert
  get_url:
    url: "{{ openssl_cacert_url }}"
    dest: "{{ openssl_cacert_file }}"
    force: yes

- name: Include mkcert CA in cacert
  shell: cat "$(mkcert -CAROOT)/rootCA.pem" >> {{ openssl_cacert_file }}