---

- block:
    - name: Check if sudo password is correct
      command: echo "Password is correct"
      changed_when: False
      become: yes
      no_log: True

  rescue:
    - name: Fails
      debug: msg='Wrong password'
    - meta: end_play

