---
#########
# NGINX #
#########

nginx_http_port: 80
nginx_https_port: 443
nginx_http2: true
nginx_default_site_root: "/usr/local/var/www"
nginx_path: /usr/local/etc/nginx
nginx_log_path: /usr/local/var/log/nginx
nginx_conf_path: "{{ nginx_path }}/nginx.conf"

nginx_site_types:
  - symfony
  - symfony-flex
  - php
  - cors
  - wordpress

#########
# SSL   #
#########

openssl_path: /usr/local/etc/openssl
openssl_certs_path: "{{ openssl_path }}/certs"
openssl_private_path: "{{ openssl_path }}/private"
openssl_cacert_file: /usr/local/etc/openssl/cacert.pem
openssl_cacert_url: https://curl.haxx.se/ca/cacert.pem