---
############
# SYSTEM   #
############
upgrade_all_packages: False
homebrew_package_state: present
playbook_dev_path: "{{ playbook_dir }}/.."
sudo_password: ""

# Use with "dev config". Examples: atom, code, pstorm, etc
edit_dev_config_with: vim

homebrew_cask_packages:
  - wkhtmltopdf
  - qlmarkdown # preview markdown
  - quicklook-json # preview json
  - qlstephen # preview all files without or with unknown extension
  - qlcolorcode # add color for code

homebrew_packages: []

mas_upgrade_all_apps: no
mas_installed_apps: []

managed_services:
  - { name: nginx, sudo: true }
  - { name: "php@{{ php_version }}" }
  - { name: dnsmasq }
  - { name: mailhog }
  - { name: mariadb }
  - { name: "postgresql@{{ postgresql_version }}" }

managed_plists:
  - { name: com.minio.minio }

############
# dotfiles #
############

zsh_theme: ys

zsh_syntax_highlighting: true
zsh_autosuggestions: false
zsh_aliases:
  - ll='ls -lh'
  - tailf='tail -f'
  - df='df -h'
  - gut="git"
  - gti="git"
  - cat="bat"

# SSH config (~/.ssh/config)
#ssh_config: |
#      Host *
#		    User example

#########
# GIT   #
#########

git_user_name: X X
git_user_email: x@exemple.fr

#  https://github.com/tj/git-extras
install_git_extras: true

use_gpg_to_sign_commit: false

#########
# PHP   #
#########

php_version: 7.3

php_supported_versions:
  - 7.3
  - 7.4

php_unsupported_versions:
  - 7.2

install_xdebug: true

php_fpm_memory_limit: 256M

# PECL
php_extensions:
  - imagick

# packages needed to build extensions
php_extensions_dependencies:
  - openldap
  - libiconv
  - imagemagick

php_custom_config:
  - section: "PHP"
    option: "max_execution_time"
    value: 120
  - section: "PHP"
    option: "display_errors"
    value: 1
  - section: "PHP"
    option: "error_reporting"
    value: "E_ALL & ~E_DEPRECATED & ~E_STRICT"
  - section: "PHP"
    option: "error_log"
    value: "/usr/local/var/log/php_errors.log"
  - section: "PHP"
    option: "memory_limit"
    value: -1
  - section: "PHP"
    option: "upload_max_filesize"
    value: "20M"
  - section: "PHP"
    option: "post_max_size"
    value: "20M"
  - section: "Date"
    option: "date.timezone"
    value: "Europe/Paris"
  - section: "Session"
    option: "session.cookie_lifetime"
    value: 604800
  - section: "Session"
    option: "session.gc_maxlifetime"
    value: 604800
  - section: "mail function"
    option: "sendmail_path"
    value: "Mailhog sendmail"
  - section: "xdebug"
    option: "xdebug.remote_port"
    value: "9001"
    when: install_xdebug
  - section: "xdebug"
    option: "xdebug.remote_enable"
    value: 1
    when: install_xdebug
  - section: "xdebug"
    option: "xdebug.profiler_enable"
    value: 1
    when: install_xdebug
  - section: "xdebug"
    option: "xdebug.profiler_output_dir"
    value: "{{ '~/dev/xdebug' | expanduser }}"
    when: install_xdebug
  - section: "xdebug"
    option: "xdebug.idekey"
    value: "mac-playbook"
    when: install_xdebug
  - section: "xdebug"
    option: "xdebug.file_link_format"
    value: "'phpstorm://open?file=%f&line=%l'"
    when: install_xdebug
  # issue between PHP 7.4, opcache and Symfony
  - section: "opcache"
    option: "opcache.enable"
    value: 0

setup_blackfire: false
blackfire_server_id: ~
blackfire_server_token: ~
blackfire_client_id: ~
blackfire_client_token: ~

composer_global_packages:
  hirak/prestissimo: "@stable"

###########
# Node    #
###########

node_version: 10

###########
# Nginx   #
###########

nginx_client_max_body_size: 5M
nginx_php_max_execution_time: 120

nginx_sites:
  - name: example
    server_name: example.localhost
    nginx_type: symfony-flex
    root: "~/dev/example/web"
    redirect_to_https: true
    https: true

#########
# DNS   #
#########

dnsmasq_domains:
  - localhost

#############
# MariaDB   #
#############

mariadb_dev_user: dev
mariadb_dev_password: dev

# dont change after bootstrap
mariadb_root_password: ohvaiN2azoof0feeDi2

################
# PostgreSQL   #
################

postgresql_version: 11

#############
# Mailhog   #
#############

mailhog_api_bind_addr: 0.0.0.0:8025
mailhog_ui_bind_addr: 0.0.0.0:8025
mailhog_smtp_bind_addr: 0.0.0.0:1025

mailhog_hostname: example.org
#mailhog_outgoing_smtp_servers:
#  my_server:
#    name: my_server
#    host: smtp.exemple.fr
#    port: "25"

#############
# Minio     #
#############

minio_plist_name: com.minio.minio
minio_access_key: AKIAIOSFODNN7EXAMPLE
minio_secret_key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
