---

############
# System   #
############

upgrade_all_packages: false
homebrew_package_state: present
playbook_dev_path: "{{ playbook_dir }}/.."
sudo_password: ""

# Use with "dev config". Examples: atom, code, pstorm, etc
edit_dev_config_with: vim

homebrew_cask_packages: []
homebrew_packages: []

mas_upgrade_all_apps: no
mas_installed_apps: []

managed_services_as_user:
  - "php@{{ php_version }}"
  - redis
  - dnsmasq
  - mailhog
  - mariadb
  - "postgresql@{{ postgresql_version }}"
  - blackfire-agent

managed_services_as_root:
  - nginx

managed_plists:
  - com.minio.minio

##################
# Certificates   #
##################

openssl_ca_file: /usr/local/etc/openssl@1.1/cert.pem

############
# dotfiles #
############

zsh_theme: ys

zsh_plugins:
  - git
  - history-substring-search
  - sudo
  - composer
  - brew
  - httpie
  - extract
  - symfony
  - zsh-syntax-highlighting

zsh_custom_plugins:
  - name: symfony
    url: https://github.com/TheGrowingPlant/symfony.plugin.zsh.git
  - name: zsh-syntax-highlighting
    url: https://github.com/zsh-users/zsh-syntax-highlighting.git

zsh_aliases:
  - ll='ls -lh'
  - tailf='tail -f'
  - df='df -h'
  - gut="git"
  - gti="git"
  - cat="bat"

# SSH config (~/.ssh/config)
#ssh_config: |
#      Host *
#		    User example

#########
# GIT   #
#########

git_user_name: X X
git_user_email: x@exemple.fr

#  https://github.com/tj/git-extras
install_git_extras: true

use_gpg_to_sign_commit: false

#########
# PHP   #
#########

php_default_version:  8.0

php_supported_versions:
  - 7.4
  - 8.0

php_unsupported_versions:
  - 7.3
  - 7.2

install_xdebug: true

php_fpm_memory_limit: 256M

# PECL
php_extensions:
#  - imagick
#  - redis
  - igbinary

# packages needed to build extensions
php_extensions_dependencies:
  - libiconv
#  - imagemagick

php_custom_config:
  - section: "PHP"
    option: "max_execution_time"
    value: 120
  - section: "PHP"
    option: "display_errors"
    value: 1
  - section: "PHP"
    option: "error_reporting"
    value: "E_ALL & ~E_DEPRECATED & ~E_STRICT"
  - section: "PHP"
    option: "error_log"
    value: "/usr/local/var/log/php_errors.log"
  - section: "PHP"
    option: "memory_limit"
    value: -1
  - section: "PHP"
    option: "upload_max_filesize"
    value: "20M"
  - section: "PHP"
    option: "post_max_size"
    value: "20M"
  - section: "Date"
    option: "date.timezone"
    value: "Europe/Paris"
  - section: "Session"
    option: "session.cookie_lifetime"
    value: 604800
  - section: "Session"
    option: "session.gc_maxlifetime"
    value: 604800
  - section: "mail function"
    option: "sendmail_path"
    value: "Mailhog sendmail"
  - section: "xdebug"
    option: "xdebug.client_port"
    value: "9003"
    when: install_xdebug
  - section: "xdebug"
    option: "xdebug.mode"
    value: 'debug'
    when: install_xdebug
  - section: "xdebug"
    option: "xdebug.output_dir"
    value: "{{ '~/dev/xdebug' | expanduser }}"
    when: install_xdebug
  - section: "xdebug"
    option: "xdebug.idekey"
    value: "mac-playbook"
    when: install_xdebug
  - section: "xdebug"
    option: "xdebug.file_link_format"
    value: "'phpstorm://open?file=%f&line=%l'"
    when: install_xdebug
  - section: "xdebug"
    option: "xdebug.log"
    value: "/usr/local/var/log/xdebug_remote.log"
    when: install_xdebug

setup_blackfire: false
blackfire_server_id: ~
blackfire_server_token: ~
blackfire_client_id: ~
blackfire_client_token: ~

composer_global_packages: []

###########
# Node    #
###########

node_version: 14

###########
# Nginx   #
###########

nginx_client_max_body_size: 5M
nginx_php_max_execution_time: 120

nginx_sites:
  - name: example
    server_name: example.localhost
    nginx_type: symfony-flex
    root: "~/dev/example/web"
    redirect_to_https: true
    https: true

nginx_system_sites:
  - "{{ mailhog_nginx_site }}"
  - "{{ minio_nginx_site }}"

nginx_certificates:
  - localhost
  - 127.0.0.1

#########
# DNS   #
#########

dnsmasq_domains:
  - localhost

#############
# MariaDB   #
#############

mariadb_dev_user: dev
mariadb_dev_password: dev

# dont change after bootstrap
mariadb_root_password: ohvaiN2azoof0feeDi2

################
# PostgreSQL   #
################

postgresql_version: 12

#############
# Mailhog   #
#############

mailhog_api_bind_addr: 0.0.0.0:8025
mailhog_ui_bind_addr: 0.0.0.0:8025
mailhog_smtp_bind_addr: 0.0.0.0:1025

mailhog_hostname: example.org
#mailhog_outgoing_smtp_servers:
#  my_server:
#    name: my_server
#    host: smtp.exemple.fr
#    port: "25"

mailhog_nginx_site:
  name: mailhog
  server_name: mailhog.localhost
  type: custom
  redirect_to_https: true
  custom_config: |
    location / {
        proxy_pass http://{{ mailhog_ui_bind_addr }};
        chunked_transfer_encoding on;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_http_version 1.1;
        proxy_redirect off;
        proxy_buffering off;
    }

#############
# Minio     #
#############

minio_plist_name: com.minio.minio
minio_access_key: AKIAIOSFODNN7EXAMPLE
minio_secret_key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

minio_nginx_site:
  name: minio
  server_name: minio.localhost
  type: custom
  redirect_to_https: true
  custom_config: |
    # To allow special characters in headers
    ignore_invalid_headers off;
    # Allow any size file to be uploaded.
    client_max_body_size 0;
    # To disable buffering
    proxy_buffering off;

    location / {
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header Host $http_host;

      proxy_connect_timeout 300;
      # Default is HTTP/1, keepalive is only enabled in HTTP/1.1
      proxy_http_version 1.1;
      proxy_set_header Connection "";
      chunked_transfer_encoding off;

      proxy_pass http://localhost:9005;
    }