---
- name: Clone oh-my-zsh repo
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: ~/.oh-my-zsh
    force: yes

- name: Capture current installed custom plugins
  find:
    paths: ~/.oh-my-zsh/custom/plugins/
    file_type: directory
  register: current_installed_zsh_custom_plugins

- name: Remove old zsh custom plugins
  file:
    state: absent
    path: "{{ item.path }}"
  when: (item.path | basename) not in (zsh_custom_plugins+['example'])|to_json
  with_items: "{{ current_installed_zsh_custom_plugins.files }}"
  loop_control:
    label: "{{ item.path | basename }}"

- name: Clone custom plugins
  git:
    repo: "{{ item.url }}"
    dest: "~/.oh-my-zsh/custom/plugins/{{ item.name }}"
    force: yes
  with_items: "{{ zsh_custom_plugins }}"
  when: item.url is defined

- name: Deploy .zprofile
  template:
    src: zprofile.j2
    dest: ~/.zprofile

- name: Deploy .zshrc
  template:
    src: zshrc.j2
    dest: ~/.zshrc

- name: Deploy .zsh_aliases
  template:
    src: zsh_aliases.j2
    dest: ~/.zsh_aliases

- name: Ensure user config file exists
  copy:
    content: ""
    dest: ~/.zshrc.local
    force: no

- name: Set zsh as default shell
  user:
    name: "{{ lookup('env','USER') }}"
    shell: /bin/zsh
  become: true

- name: Add conf.d in ssh directory
  file:
    state: directory
    path: "~/.ssh/conf.d"

- name: Add SSH config
  template:
    src: "ssh_config.j2"
    dest: ~/.ssh/config

- name: Deploy .sqliterc
  copy:
    src: sqliterc
    dest: ~/.sqliterc

- name: Deploy global editorconfig
  template:
    src: editorconfig.j2
    dest: ~/.editorconfig

- name: Fix permissions with zsh completions
  shell: "chmod go-w '{{ brew_prefix }}/share' && chmod -R go-w '{{ brew_prefix }}/share/zsh'"