---
- name: Create my.cnf.d
  file:
    path: /usr/local/etc/my.cnf.d
    state: directory

# https://github.com/Homebrew/brew/issues/5783
- name: Create file to keep /usr/local/etc/my.cnf.d/
  file:
    path: /usr/local/etc/my.cnf.d/KEEP_DIR
    state: touch

- name: Create log path
  file:
    path: "{{ mariadb_log_path }}"
    state: directory

- name: Install mariadb
  homebrew:
    name: mariadb
    state: "{{ homebrew_package_state }}"

- name: Restart mariadb
  shell: brew services restart mariadb
  args:
    creates: "{{ mariadb_socket }}"

- name: Wait for mariadb start
  wait_for:
    path: "{{ mariadb_socket }}"

- name: Set root password
  shell: mysqladmin -u root password '{{ mariadb_root_password }}'
  become: yes
  args:
    creates: ~/.my.cnf

- name: Create {{ mariadb_dev_user }} user of MariaDB
  command: mysql -u root -p{{ mariadb_root_password }} -NBe "CREATE USER '{{ mariadb_dev_user }}'@'{{ item }}' IDENTIFIED BY '{{ mariadb_dev_password }}'; GRANT ALL PRIVILEGES ON *.* TO '{{ mariadb_dev_user }}'@'{{ item }}' WITH GRANT OPTION; FLUSH PRIVILEGES;"
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
  args:
    creates: ~/.my.cnf

- name: Add my.cnf
  template: >
    src=my.cnf.j2
    dest=~/.my.cnf
    force=yes

- name: Get list of hosts for the anonymous user
  command: mysql -NBe 'SELECT Host FROM mysql.user WHERE User = ""'
  register: mysql_anonymous_hosts
  changed_when: false

- name: Remove anonymous users
  command: mysql -u root -p{{ mariadb_root_password }} -NBe "DROP USER ''@'{{ item }}'"
  with_items: "{{ mysql_anonymous_hosts.stdout_lines }}"

- name: Check if test database exists
  command: mysql -u root -p{{ mariadb_root_password }} -NBe "SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'test'"
  register: mysql_check_test_database_exists
  changed_when: false

- name: Remove MySQL test database
  command: mysql -u root -p{{ mariadb_root_password }} -NBe "DROP DATABASE test"
  when: mysql_check_test_database_exists.stdout_lines|length != 0
