---
- name: create my.cnf.d
  file:
    path: /usr/local/etc/my.cnf.d
    state: directory

- name: create log path
  file:
    path: "{{ mariadb_log_path }}"
    state: directory

- name: homebrew install mariadb
  homebrew:
    name: mariadb
    state: "{{ homebrew_package_state }}"

- name: restart mariadb
  shell: brew services restart mariadb
  args:
    creates: "{{ mariadb_socket }}"

- name: Wait for mariadb start
  wait_for:
    path: "{{ mariadb_socket }}"

- name: set root password
  shell: mysqladmin -u root password '{{ mariadb_root_password }}'
  args:
    creates: ~/.my.cnf

- name: Create {{ mariadb_dev_user | mandatory }} user of MariaDB
  command: mysql -u root -p{{ mariadb_root_password }} -NBe "CREATE USER '{{ mariadb_dev_user | mandatory }}'@'{{ item }}' IDENTIFIED BY '{{ mariadb_dev_password | mandatory }}'; GRANT ALL PRIVILEGES ON *.* TO '{{ mariadb_dev_user | mandatory }}'@'{{ item }}' WITH GRANT OPTION; FLUSH PRIVILEGES;"
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
  args:
    creates: ~/.my.cnf

- name: add my.cnf
  template: >
    src=my.cnf.j2
    dest=~/.my.cnf
    force=yes

- name: Get list of hosts for the anonymous user
  command: mysql -NBe 'SELECT Host FROM mysql.user WHERE User = ""'
  register: mysql_anonymous_hosts
  changed_when: false

- name: Remove anonymous users
  command: mysql -u root -p{{ mariadb_root_password }} -NBe "DROP USER ''@'{{ item }}'"
  with_items: "{{ mysql_anonymous_hosts.stdout_lines }}"

- name: Check if test database exists
  command: mysql -u root -p{{ mariadb_root_password }} -NBe "SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'test'"
  register: mysql_check_test_database_exists
  changed_when: false

- name: Remove MySQL test database
  command: mysql -u root -p{{ mariadb_root_password }} -NBe "DROP DATABASE test"
  when: mysql_check_test_database_exists.stdout_lines|length != 0

- name: génération de la config pour la page d'accueil
  template:
    src: local-homepage/config.php.j2
    dest: "{{ playbook_dev_path | realpath }}/local-homepage/config/mariadb.config.php"

- name: create my.cnf.d
  file:
    path: /usr/local/etc/my.cnf.d
    state: directory
