---

- set_fact:
    mariadb_package_name: "mariadb@{{ mariadb_version }}"

- name: Create my.cnf.d
  file:
    path: "{{ brew_prefix }}/etc/my.cnf.d"
    state: directory

# https://github.com/Homebrew/brew/issues/5783
- name: Create file to keep /etc/my.cnf.d/
  file:
    path: "{{ brew_prefix }}/etc/my.cnf.d/KEEP_DIR"
    state: touch

- name: Create log path
  file:
    path: "{{ mariadb_log_path }}"
    state: directory

- name: Install mariadb
  homebrew:
    name: "{{ mariadb_package_name }}"
    state: "{{ homebrew_package_state }}"

- name: Stop mariadb
  shell: "brew services stop {{ mariadb_package_name }}"

- name: Start mariadb
  shell: brew services start {{ mariadb_package_name }}
  args:
    creates: "{{ mariadb_socket }}"

- name: Wait for mariadb start
  wait_for:
    path: "{{ mariadb_socket }}"

- name: Get brew prefix for MariaDB
  shell: "brew --prefix {{ mariadb_package_name }}"
  register: brew_prefix_mariadb
  changed_when: False

- set_fact:
    mariadb_bin_path: "{{ brew_prefix_mariadb.stdout }}/bin"

- name: Add "~/.load_mariadb" file to add MariaDB to $PATH
  template:
    src: load_mariadb.j2
    dest: ~/.load_mariadb
    mode: "u=rxw,g=rx,o=rx"

- name: Set root password
  shell: "{{ mariadb_bin_path }}/mysqladmin -u root password '{{ mariadb_root_password }}'"
  become: yes
  args:
    creates: ~/.my.cnf

- name: Create {{ mariadb_dev_user }} user of MariaDB
  command: "{{ mariadb_bin_path }}/mysql -u root -p{{ mariadb_root_password }} -NBe \"CREATE USER '{{ mariadb_dev_user }}'@'{{ item }}' IDENTIFIED BY '{{ mariadb_dev_password }}'; GRANT ALL PRIVILEGES ON *.* TO '{{ mariadb_dev_user }}'@'{{ item }}' WITH GRANT OPTION; FLUSH PRIVILEGES;\""
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
  args:
    creates: ~/.my.cnf

- name: Add my.cnf
  template: >
    src=my.cnf.j2
    dest=~/.my.cnf
    force=yes

- name: Get list of hosts for the anonymous user
  command: "{{ mariadb_bin_path }}/mysql -NBe 'SELECT Host FROM mysql.user WHERE User = \"\"'"
  register: mysql_anonymous_hosts
  changed_when: false

- name: Remove anonymous users
  command: "{{ mariadb_bin_path }}/mysql -u root -p{{ mariadb_root_password }} -NBe \"DROP USER ''@'{{ item }}'\""
  with_items: "{{ mysql_anonymous_hosts.stdout_lines }}"

- name: Check if test database exists
  command: "{{ mariadb_bin_path }}/mysql -u root -p{{ mariadb_root_password }} -NBe \"SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'test'\""
  register: mysql_check_test_database_exists
  changed_when: false

- name: Remove MySQL test database
  command: "{{ mariadb_bin_path }}/mysql -u root -p{{ mariadb_root_password }} -NBe \"DROP DATABASE test\""
  when: mysql_check_test_database_exists.stdout_lines|length != 0

- name: Create config for homepage
  template:
    src: local-homepage/config.php.j2
    dest: "{{ playbook_dev_path | realpath }}/local-homepage/config/mariadb.config.php"
