---
- name: Add git config
  template:
    src: gitconfig.j2
    dest: ~/.gitconfig
    force: yes

- name: Add gitignore
  copy:
    src: gitignore_global
    dest: ~/.gitignore_global

- name: Add git commit template
  copy:
    src: git_commit_msg.txt
    dest: ~/.git_commit_msg.txt

- name: Install git-extras
  homebrew:
    name: git-extras
    state: present
  when: install_git_extras
