---
- name: Upgrade all mas apps (if configured)
  command: mas upgrade
  when: mas_upgrade_all_apps|bool

- name: Upgrade all binaries
  homebrew:
    update_homebrew: yes
    upgrade_all: yes
  when: upgrade_all_packages|bool
