---
- command: "brew services {{ service_state }} {{ item.name }}"
  with_items: "{{ managed_services }}"
  become: "{{ item.sudo|default(false) }}"
  ignore_errors: true

- command: "launchctl unload /Users/{{ lookup('env','USER') }}/Library/LaunchAgents/{{ item.name }}.plist"
  with_items: "{{ managed_plists }}"
  when: service_state == 'stop' or service_state == 'restart'
  become: "{{ item.sudo|default(false) }}"
  ignore_errors: true

- command: "launchctl load /Users/{{ lookup('env','USER') }}/Library/LaunchAgents/{{ item.name }}.plist"
  with_items: "{{ managed_plists }}"
  when: service_state == 'start' or service_state == 'restart'
  become: "{{ item.sudo|default(false) }}"
  ignore_errors: true
