#!/bin/sh

read -s -p "Veuillez saisir votre mot de passe SUDO : " SUDO_PASSWORD

echo "\n\nGénération du mot de passe Ansible en cours ..."
ANSIBLE_PASSWORD=`date +%s | base64 | head -c 32`
/usr/bin/security add-generic-password -a "$USER" -s ansible-mac-dev-playbook -w "$ANSIBLE_PASSWORD" -U

echo "Chiffrement du mot de passe en cours ..."
ansible-vault encrypt_string $SUDO_PASSWORD --name 'sudo_password' | pbcopy
echo "Copie du mot de passe SUDO chiffré dans le presse papier en cours ..."

echo "\nVous pouvez maintenant coller le mot de passe dans le fichier config.yml"