#!/bin/sh

read -s -p "Please enter your SUDO password: " SUDO_PASSWORD

echo "\n\nAnsible password generation in progress..."
ANSIBLE_PASSWORD=`date +%s | base64 | head -c 32`
/usr/bin/security add-generic-password -a "$USER" -s ansible-mac-dev-playbook -w "$ANSIBLE_PASSWORD" -U

echo "Password encryption in progress..."
ansible-vault encrypt_string $SUDO_PASSWORD --name 'sudo_password' | pbcopy
echo "Copy of encrypted SUDO password to the clipboard..."

echo "\nYou can now paste the password into the config.yml file"