---
- name: stop minio
  shell: "launchctl unload -w {{ minio_plist_path }}"
  ignore_errors: yes

- name: homebrew install minio
  homebrew:
    name:
      - minio/stable/minio
      - minio/stable/mc
    state: "{{ homebrew_package_state }}"

- name: add plist file
  template:
    src: minio.plist.j2
    dest: "{{ minio_plist_path }}"

- name: start minio
  shell: "launchctl load -w {{ minio_plist_path }}"

- name: Generate config for local homepage
  template:
    src: local-homepage/config.php.j2
    dest: "{{ playbook_dev_path | realpath }}/local-homepage/config/minio.config.php"
