---
- name: Stop minio
  shell: "launchctl unload -w {{ minio_plist_path }}"
  ignore_errors: yes

- name: Install minio
  homebrew:
    name:
      - minio/stable/minio
      - minio/stable/mc
    state: "{{ homebrew_package_state }}"

- name: Add plist file
  template:
    src: minio.plist.j2
    dest: "{{ minio_plist_path }}"

- name: Fix right on log directory
  file:
    path: /usr/local/var/log/minio
    state: directory
    recurse: yes
    owner: "{{ lookup('env','USER') }}"
  become: yes

- name: Start minio
  shell: "launchctl load -w {{ minio_plist_path }}"

- name: Wait for minio to start
  wait_for:
    port: "{{ minio_port }}"
    delay: 10

- name: Configure mc
  shell: "mc config host add minio http://localhost:{{ minio_port }} {{ minio_access_key }} {{ minio_secret_key }}"
