---
- name: Tap blackfire homebrew repositories
  homebrew_tap:
    tap: "{{ item }}"
    state: present
  with_items: "{{ homebrew_tap }}"

- name: Update homebrew
  homebrew:
    update_homebrew: yes
  when: upgrade_all_packages|bool

- name: Install homebrew packages
  homebrew:
    name: "{{ homebrew_base_packages + homebrew_packages|default([]) }}"
    state: "{{ homebrew_package_state }}"

- name: Install homebrew cask packages
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items: "{{ homebrew_cask_packages }}"
  ignore_errors: true

- name: List installed MAS apps
  command: mas list
  register: mas_list
  check_mode: no
  changed_when: false

- name: Ensure configured MAS apps are installed
  command: mas install "{{ item.id|default(item) }}"
  with_items: "{{ mas_installed_apps }}"
  when: (item.id | default(item) | string) not in mas_list.stdout
