---
- name: Tap homebrew repositories
  homebrew_tap:
    tap: "{{ item }}"
    state: present
  loop: "{{ homebrew_tap }}"

- name: Update homebrew
  homebrew:
    update_homebrew: yes
  when: upgrade_all_packages|bool

- name: Install homebrew packages
  homebrew:
    name: "{{ homebrew_base_packages + homebrew_packages|default([]) }}"
    state: "{{ homebrew_package_state }}"

- name: Install homebrew cask packages
  homebrew_cask:
    name: "{{ item }}"
    state: present
  loop: "{{ homebrew_cask_packages }}"
  ignore_errors: true

- name: Ensure configured MAS apps are installed
  community.general.mas:
    id: "{{ mas_installed_apps }}"
    state: "{{ mas_package_state }}"
