---
- name: "{{ php_current_version }} - Install"
  homebrew:
    name: "shivammathur/php/php@{{ php_current_version }}"
    state: "{{ homebrew_package_state }}"

- name: "{{ php_current_version }} - Get PECL path"
  shell: "brew --prefix shivammathur/php/php@{{ php_current_version }}"
  register: brew_prefix_php
  changed_when: False

- name: "{{ php_current_version }} - Register PECL binary"
  set_fact:
    pecl_bin: "{{ brew_prefix_php.stdout }}/bin/pecl"

- name: "{{ php_current_version }} - Update PECL"
  shell: "{{ pecl_bin }} channel-update pecl.php.net"
  register: pecl_update_result
  changed_when: "'succeeded' in pecl_update_result.stdout"

- name: "{{ php_current_version }} - Install extensions with PECL"
  shell: "{{ pecl_bin }} install {{ item }}"
  register: pecl_result
  changed_when: "pecl_result.rc == 0"
  failed_when: "not (('already installed' in pecl_result.stdout) or ('install ok:' in pecl_result.stdout))"
  with_items: "{{ php_extensions }}"

- name: "{{ php_current_version }} - Install xdebug"
  shell: "{{ pecl_bin }} install {{ xdebug_package }}"
  register: pecl_result
  changed_when: "pecl_result.rc == 0"
  failed_when: "not (('already installed' in pecl_result.stdout) or ('install ok:' in pecl_result.stdout))"
  when: install_xdebug

- name: "{{ php_current_version }} - Remove loading of xdebug in php.ini"
  lineinfile:
    path: "/usr/local/etc/php/{{ php_current_version }}/php.ini"
    state: absent
    regexp: '^zend_extension="xdebug.so"'
  when: install_xdebug

- name: "{{ php_current_version }} - Check if ext-xdebug.ini exists"
  stat:
    path: "/usr/local/etc/php/{{ php_current_version }}/conf.d/ext-xdebug.ini"
  register: stat_ext_debug_ini
  when: install_xdebug

- name: "{{ php_current_version }} - Check if ext-xdebug.ini.disabled exists"
  stat:
    path: "/usr/local/etc/php/{{ php_current_version }}/conf.d/ext-xdebug.ini.disabled"
  register: stat_ext_debug_ini_disabled
  when: install_xdebug

- name: "{{ php_current_version }} - Load xdebug with custom file"
  lineinfile:
    path: "/usr/local/etc/php/{{ php_current_version }}/conf.d/ext-xdebug.ini"
    state: present
    line: 'zend_extension="xdebug.so"'
    create: yes
  when: install_xdebug and not stat_ext_debug_ini.stat.exists and not stat_ext_debug_ini_disabled.stat.exists

- name: "{{ php_current_version }} - Set FPM config"
  template:
    src: php-fpm.conf.j2
    dest: "/usr/local/etc/php/{{ php_current_version }}/php-fpm.conf"

- name: "{{ php_current_version }} - Delete old fpm config"
  file:
    dest: "/usr/local/etc/php/{{ php_current_version }}/php-fpm.d/www.conf"
    state: absent

- name: "{{ php_current_version }} - Add configs"
  ini_file:
    dest: "{{ php_custom_config_file }}"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  when: item.when|default(true)
  become: true
  with_items: "{{ php_custom_config }}"
