---
- name: Install PHP
  homebrew:
    name: "php@{{ php_version }}"
    state: latest

- name: Install extensions dependencies
  homebrew:
    name: "{{ item }}"
    state: latest
  with_items: "{{ php_extensions_dependencies }}"

- name: Get PECL path
  shell: "brew --prefix php@{{ php_version }}"
  register: brew_prefix_php
  changed_when: False

- set_fact:
    pecl_bin: "{{ brew_prefix_php.stdout }}/bin/pecl"

- name: Update PECL
  shell: "{{ pecl_bin }} channel-update pecl.php.net"
  register: pecl_update_result
  changed_when: "'succeeded' in pecl_update_result.stdout"

- name: Install extensions with PECL
  shell: "{{ pecl_bin }} install {{ item }}"
  register: pecl_result
  changed_when: "pecl_result.rc == 0"
  failed_when: "not (('already installed' in pecl_result.stdout) or ('install ok:' in pecl_result.stdout))"
  with_items: "{{ php_extensions }}"
  notify: restart php-fpm

- name: Install xdebug
  shell: "{{ pecl_bin }} install xdebug"
  register: pecl_result
  changed_when: "pecl_result.rc == 0"
  failed_when: "not (('already installed' in pecl_result.stdout) or ('install ok:' in pecl_result.stdout))"
  when: install_xdebug
  notify: restart php-fpm

- name: Remove loading of xdebug in php.ini
  lineinfile:
    path:  "/usr/local/etc/php/{{ php_version }}/php.ini"
    state: absent
    regexp: '^zend_extension="xdebug.so"'
  when: install_xdebug
  notify: restart php-fpm

- name: Load xdebug with custom file
  lineinfile:
    path:  "/usr/local/etc/php/{{ php_version }}/conf.d/ext-xdebug.ini"
    state: present
    line: 'zend_extension="xdebug.so"'
    create: yes
  when: install_xdebug
  notify: restart php-fpm

- name: Set FPM config
  template:
    src: php-fpm.conf.j2
    dest: '/usr/local/etc/php/{{ php_version }}/php-fpm.conf'
  notify: restart php-fpm

- name: Add configs
  ini_file:
    dest: "{{ php_custom_config_file }}"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  when: item.when|default(true)
  become: true
  with_items: "{{ php_custom_config }}"
  notify: restart php-fpm

- name: Add "~/.load_php" file to add PHP to $PATH
  template:
    src: load_php.j2
    dest: ~/.load_php
    mode: "u=rxw,g=rx,o=rx"
