---
- name: Check that default PHP version is supported
  fail:
    msg: "Default PHP version {{ php_version }} is not supported"
  when: php_version|float not in php_supported_versions

- name: Uninstall unsupported PHP versions
  homebrew:
    name: "php@{{ item }}"
    state: absent
  with_items: "{{ php_unsupported_versions }}"

- name: Stop all supported PHP-FPM
  shell: "brew services stop php@{{ item }} || true"
  with_items: "{{ php_supported_versions }}"
  ignore_errors: true

- name: Install extensions dependencies
  homebrew:
    name: "{{ php_extensions_dependencies|default([]) }}"
    state: "{{ homebrew_package_state }}"

- name: Install PHP
  include_tasks: install_php.yml
  with_items: "{{ php_supported_versions }}"
  loop_control:
    loop_var: php_current_version

- name: Setup sphp
  template:
    src: sphp.sh.j2
    dest: "/usr/local/bin/sphp"
    mode: 0755

- name: Start default PHP-FPM
  command: "sphp {{ php_version }}"
