---
- name: Tap shivammathur/php homebrew repository
  homebrew_tap:
    tap: "{{ php_homebrew_tap }}"
    state: present

- name: Uninstall PHP versions
  homebrew:
    name: "shivammathur/php/php@{{ item }}"
    state: absent
  with_items: "{{ php_all_versions | difference(php_versions) }}"

- name: Install extensions dependencies
  homebrew:
    name: "{{ php_extensions_dependencies|default([]) }}"
    state: "{{ homebrew_package_state }}"

- name: Install PHP
  include_tasks: install_php.yml
  with_items: "{{ php_versions }}"
  loop_control:
    loop_var: php_current_version

- name: "brew link default version"
  shell: "brew link --overwrite php@{{ php_default_version }}"
  register: php_brew_link_result
  changed_when: "'Already linked' not in php_brew_link_result.stdout"