---

- name: Check if drush 8 is installed.
  stat: "path={{ drush8_path }}"
  register: drush8_bin

- name: Download and install drush 8 into the target directory.
  get_url:
    url="{{ drush8_url }}"
    dest="{{ drush8_path }}"
    mode=0755
  when: not drush8_bin.stat.exists
