---

- name: Add "dev" binary
  template:
    src: dev.j2
    dest: "{{ brew_prefix }}/bin/dev"
    mode: "u=rxw,g=rx,o=rx"
  become: yes

- name: Configure autocompletion for the "dev" binary
  template:
    src: autocomplete.j2
    dest: "{{ brew_prefix }}/share/zsh/site-functions/_dev"
    mode: "u=rxw,g=rx,o=rx"

- name: Configure editor for "dev config"
  template:
    src: dev_config_env.j2
    dest: ~/.dev_config_env
    mode: "u=rw,g=r,o=r"