---
- name: Tap blackfire homebrew repository
  homebrew_tap:
    tap: "{{ blackfire_homebrew_tap }}"
    state: present

- name: Install Blackfire probe
  homebrew:
    name: "blackfire-php{{ item|replace('.', '') }}"
    state: latest
  with_items: "{{ php_supported_versions }}"

- name: Install Blackfire agent
  homebrew:
    name: blackfire-agent
    state: latest

- name: Add config for Blackfire agent
  template:
    src: agent.j2
    dest: "{{ blackfire_agent_config_path }}"
  notify:
    - restart blackfire-agent

- name: Add config for Blackfire
  template:
    src: blackfire.ini.j2
    dest: "{{ blackfire_config_path }}"
