---
- name: Tap blackfire homebrew repository
  homebrew_tap:
    tap: "{{ blackfire_homebrew_tap }}"
    state: present

- name: Remove old Blackfire agent
  homebrew:
    name: blackfire-agent
    state: absent

- name: Remove old config file
  file:
    path: "{{ blackfire_config_path }}"
    state: absent

- name: Install Blackfire probe
  homebrew:
    name: "blackfire-php{{ item|replace('.', '') }}"
    state: latest
  with_items: "{{ php_supported_versions }}"

- name: Install Blackfire
  homebrew:
    name: blackfire
    state: latest

- name: Add config for Blackfire agent
  template:
    src: agent.j2
    dest: "{{ blackfire_agent_config_path }}"
  notify:
    - Restart blackfire
