- hosts: all
  vars_files:
    - ../default.config.yml
  vars_prompt:
    - name: "service_state"
      prompt: "Service state (start/stop/restart)"
      default: "start"
      private: no
  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - ../config.yml
        - ../config_php.yml
      tags: always
  roles:
    - role: check_sudo_access
      tags: always
    - manage_services
