---

- name: Install mailhog
  homebrew:
    name: mailhog
    state: "{{ homebrew_package_state }}"

- name: Add custom outgoing smtp config
  template:
    src: mailhog_smtp.json.j2
    dest: "{{ mailhog_outgoing_smtp_file }}"
    force: yes
  when: mailhog_outgoing_smtp_servers is defined
  notify: restart mailhog

- name: Add custom plist for mailhog
  template:
    src: plist.j2
    dest: "{{ mailhog_plist_file }}"
    force: yes
  notify: restart mailhog

- name: Generate config for local homepage
  template:
    src: local-homepage/config.php.j2
    dest: '{{ playbook_dev_path | realpath }}/local-homepage/config/mailhog.config.php'